import Header from "@/components/Header";

import Footer from "@/components/Footer";


export default function Tos() {
  return (
    <div className="min-h-screen">
      <Header />
      <div className="max-w-4xl mt-5 mx-auto px-4 py-8 sm:px-6 lg:px-8">
      <div className="p-6 md:p-8">
        <h1 className="text-3xl font-bold text-gray-900 mb-6 text-center">Terms of Service</h1>
        <p className="text-gray-600 mb-8 text-center">Effective Date: 09/05/2025</p>

        <div className="space-y-8">
          {/* Section 1 */}
          <div>
            <h2 className="text-xl font-semibold text-gray-800 mb-3">1. Acceptance of Terms</h2>
            <p className="text-gray-700">
              By accessing or using <span className="font-medium">Buildwise</span>, operated by <span className="font-medium">Metaverse Lab Limited</span>, you agree to comply with and be bound by these Terms of Service.
            </p>
          </div>

          {/* Section 2 */}
          <div>
            <h2 className="text-xl font-semibold text-gray-800 mb-3">2. Use of the Service</h2>
            <ul className="list-disc pl-5 space-y-2 text-gray-700">
              <li>You must be at least <span className="font-medium">18 years old</span> to use Buildwise.</li>
              <li>You agree to use Buildwise only for <span className="font-medium">lawful purposes</span>.</li>
            </ul>
          </div>

          {/* Section 3 */}
          <div>
            <h2 className="text-xl font-semibold text-gray-800 mb-3">3. User Accounts</h2>
            <ul className="list-disc pl-5 space-y-2 text-gray-700">
              <li>You must provide <span className="font-medium">accurate and complete</span> information when creating an account.</li>
              <li>You are responsible for maintaining the <span className="font-medium">confidentiality of your account credentials</span>.</li>
            </ul>
          </div>

          {/* Section 4 */}
          <div>
            <h2 className="text-xl font-semibold text-gray-800 mb-3">4. Content and Intellectual Property</h2>
            <ul className="list-disc pl-5 space-y-2 text-gray-700">
              <li>Users have full rights to use the content generated by <span className="font-medium">Buildwise</span> as they see fit.</li>
              <li>Users retain rights to their original content uploaded to Buildwise.</li>
            </ul>
          </div>

          {/* Section 5 */}
          <div>
            <h2 className="text-xl font-semibold text-gray-800 mb-3">5. Communication and Marketing</h2>
            <p className="text-gray-700">
              By registering, you consent to receive emails from us, including <span className="font-medium">newsletters and promotional materials</span>. You can <span className="font-medium">unsubscribe</span> at any time.
            </p>
          </div>

          {/* Section 6 */}
          <div>
            <h2 className="text-xl font-semibold text-gray-800 mb-3">6. Payment and Billing</h2>
            <ul className="list-disc pl-5 space-y-2 text-gray-700">
              <li>Payments for services are processed via <span className="font-medium">Stripe</span>.</li>
              <li>All fees are <span className="font-medium">non-refundable</span> unless otherwise specified.</li>
            </ul>
          </div>

          {/* Section 7 */}
          <div>
            <h2 className="text-xl font-semibold text-gray-800 mb-3">7. Termination</h2>
            <p className="text-gray-700">
              We reserve the right to <span className="font-medium">suspend or terminate</span> your account if you violate these Terms of Service.
            </p>
          </div>

          {/* Section 8 */}
          <div>
            <h2 className="text-xl font-semibold text-gray-800 mb-3">8. Limitation of Liability</h2>
            <ul className="list-disc pl-5 space-y-2 text-gray-700">
              <li>Buildwise is provided <span className="font-medium">"as is."</span> We do not guarantee its availability or functionality.</li>
              <li><span className="font-medium">Metaverse Lab Limited</span> is not liable for any <span className="font-medium">direct, indirect, incidental, or consequential damages</span> resulting from your use of the service.</li>
            </ul>
          </div>

          {/* Section 9 */}
          <div>
            <h2 className="text-xl font-semibold text-gray-800 mb-3">9. Changes to Terms</h2>
            <p className="text-gray-700">
              We may update these Terms of Service. You will be notified of significant changes via <span className="font-medium">email or through our website</span>.
            </p>
          </div>

          {/* Section 10 */}
          <div>
            <h2 className="text-xl font-semibold text-gray-800 mb-3">10. Governing Law</h2>
            <p className="text-gray-700">
              These terms are governed by the <span className="font-medium">laws of Hong Kong</span>.
            </p>
          </div>

          {/* Section 11 */}
          <div>
            <h2 className="text-xl font-semibold text-gray-800 mb-3">11. Contact Information</h2>
            <p className="text-gray-700">
              For questions about these Terms of Service, please contact us at:
              <br />
              <span className="font-medium">📧 charles@voxelai.ai</span>
            </p>
          </div>

          {/* WhatsApp Section */}
          <div className="border-t pt-6 mt-6">
            <h2 className="text-xl font-semibold text-gray-800 mb-4">12. WhatsApp Business Messaging Policy Compliance</h2>
            
            <div className="space-y-4">
              <div>
                <h3 className="font-medium text-gray-800 mb-2">12.1 Opt-In and Communications</h3>
                <p className="text-gray-700">
                  By providing your phone number and opting in to receive communications via <span className="font-medium">WhatsApp</span>, you consent to being contacted by <span className="font-medium">Buildwise</span> for the purposes outlined in these Terms of Service. You understand that:
                </p>
                <ul className="list-disc pl-5 mt-2 space-y-1 text-gray-700">
                  <li>You will only receive messages relevant to your use of Buildwise, such as service updates or support.</li>
                  <li>You can <span className="font-medium">opt out</span> of WhatsApp communications at any time by contacting us or following opt-out instructions in the messages.</li>
                </ul>
              </div>

              <div>
                <h3 className="font-medium text-gray-800 mb-2">12.2 Data Usage and Privacy</h3>
                <p className="text-gray-700">
                  All data collected and used in WhatsApp communications complies with applicable <span className="font-medium">data protection laws</span> and our <span className="font-medium">Privacy Policy</span>. Buildwise will not share or misuse your WhatsApp data.
                </p>
              </div>

              <div>
                <h3 className="font-medium text-gray-800 mb-2">12.3 Prohibited Use</h3>
                <p className="text-gray-700">
                  You agree not to use Buildwise's WhatsApp services to share <span className="font-medium">sensitive personal information</span>, including payment details or personal identification numbers. Buildwise will never request sensitive information via WhatsApp.
                </p>
              </div>

              <div>
                <h3 className="font-medium text-gray-800 mb-2">12.4 Escalation Paths</h3>
                <p className="text-gray-700">
                  If you need assistance, Buildwise provides support through:
                  <br />
                  <span className="font-medium">📧 charles@voxelai.ai</span>
                </p>
              </div>

              <div>
                <h3 className="font-medium text-gray-800 mb-2">12.5 Compliance with WhatsApp Policies</h3>
                <p className="text-gray-700">
                  Buildwise operates its WhatsApp Business communications in compliance with <span className="font-medium">WhatsApp's Business Messaging Policy</span>. We do not send unsolicited messages.
                </p>
              </div>

              <div>
                <h3 className="font-medium text-gray-800 mb-2">12.6 Feedback and Reporting</h3>
                <p className="text-gray-700">
                  If you believe a message from Buildwise violates these Terms, report it to:
                  <br />
                  <span className="font-medium">📧 charles@voxelai.ai</span>
                </p>
              </div>
            </div>
          </div>
        </div>
       </div>
      </div>
      <Footer />
    </div>
  );
}
